# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1313b2935adb4d58f024ecd35b3a994814b495a6c9a26517e4c6a9a1f286f8e2e68ef018cfc12a76d3c60900016e69b4cb96d784f77a6b251fe93d485cd5a21

test:
  secret_key_base: 327c392dbb0aeee2d2ab22ac6391d50e92256ffcf0e902897b514440560a1c74e5d61c90accf45f8fc6658aa0b1df6fb095de298585432e3e6e1afca0114361a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
