User.destroy_all
Story.destroy_all
Category.destroy_all
Location.destroy_all

u1 = User.create!(email: "j@ke.wf", password: "password")

# By using u1.stories -> we automatically populate user_id in that story
# s1 = u1.stories.create(title: "Amazing story", content: "Here is a story")

# Categories
cat1 = Category.create!(name: "🛁")      # washing      SMILEYS & PEOPLE
cat2 = Category.create!(name: "💩👊✴")   # shit hit the fan
cat3 = Category.create!(name: "💪")      # working out
cat4 = Category.create!(name: "💘")      # romantic 
cat5 = Category.create!(name: "😀")      # happy 
cat6 = Category.create!(name: "😎")      # cool
cat7 = Category.create!(name: "😉")      # cheeky
cat8 = Category.create!(name: "😊")      # chuffed
cat9 = Category.create!(name: "😇")      # saintly
cat10 = Category.create!(name: "😮")     # shocking
cat11 = Category.create!(name: "😜")     # wild/ messy
cat12 = Category.create!(name: "😕")     # wtf/ confused
cat13 = Category.create!(name: "👮")     # police
cat14 = Category.create!(name: "🎅")     # christmas 
cat15 = Category.create!(name: "👯")     # dancing girls
cat16 = Category.create!(name: "💇")     # haircut
cat17 = Category.create!(name: "👰")     # wedding
cat18 = Category.create!(name: "💃")     # dancing
cat19 = Category.create!(name: "👪")     # family
cat20 = Category.create!(name: "👊")     # fighting
cat21 = Category.create!(name: "👅")     # cheeky
cat22 = Category.create!(name: "💋")     # flirty
cat23 = Category.create!(name: "🙈")     # cringe/ embarassed     NATURE
cat24 = Category.create!(name: "🐶")     # dog/ pet related
cat25 = Category.create!(name: "🐱")     # cat/ pet related
cat26 = Category.create!(name: "🐯")     # kinky/ cheeky 
cat27 = Category.create!(name: "🐎")     # horse racing/ equestrian
cat28 = Category.create!(name: "🐮")     # cow
cat29 = Category.create!(name: "🐷")     # pig/ greedy
cat30 = Category.create!(name: "🐗")     # such a bore(!)
cat31 = Category.create!(name: "🐽")     # greedy/ smelly
cat32 = Category.create!(name: "🐘")     # elephant
cat33 = Category.create!(name: "🐪")     # camel
cat34 = Category.create!(name: "🐰")     # rabbit/ easter
cat35 = Category.create!(name: "🐔")     # chicken
cat36 = Category.create!(name: "🐣")     # birth/ hatching chicken
cat37 = Category.create!(name: "🐸")     # frog
cat38 = Category.create!(name: "🐍")     # snake
cat39 = Category.create!(name: "🐳")     # whale
cat40 = Category.create!(name: "🐬")     # dolphin
cat41 = Category.create!(name: "🐟")     # fish
cat42 = Category.create!(name: "🐜")     # ant
cat43 = Category.create!(name: "🐝")     # bee
cat44 = Category.create!(name: "🌺")     # flower
cat45 = Category.create!(name: "💐")     # bouquet
cat46 = Category.create!(name: "🌹")     # rose
cat47 = Category.create!(name: "🌴")     # palm tree/ paradise
cat48 = Category.create!(name: "🌲")     # tree
cat49 = Category.create!(name: "🌳")     # bushy tree
cat50 = Category.create!(name: "🌵")     # cactus
cat51 = Category.create!(name: "🌿")     # herb
cat52 = Category.create!(name: "🍀")     # good luck/ 4 leaf clover 
cat53 = Category.create!(name: "🌻")     # sunflower
cat54 = Category.create!(name: "🌱")     # seedling/ growth
cat55 = Category.create!(name: "🍂")     # Autumn
cat56 = Category.create!(name: "🌍")     # global
cat57 = Category.create!(name: "🌊 ")    # waves/ wavey/ surfing
cat58 = Category.create!(name: "🌕")     # full moon
cat59 = Category.create!(name: "🌙")     # moon
cat60 = Category.create!(name: "☀️")     # sunny
cat61 = Category.create!(name: "☁️")     # cloud/ morbid/ depressing  
cat62 = Category.create!(name: "🌞")     # smiling sun
cat63 = Category.create!(name: "☂")     # umbrella/ raining
cat64 = Category.create!(name: "❄️")      # snow       
cat65 = Category.create!(name: "🌠")     # shooting star
cat66 = Category.create!(name: "🔥")     # fire
cat67 = Category.create!(name: "⚡")     # lightening 
cat68 = Category.create!(name: "⭐")     # star
cat69 = Category.create!(name: "🍇")     # grapes    FOOD AND DRINK
cat70 = Category.create!(name: "🍋")     # lemon
cat71 = Category.create!(name: "🍉")     # watermelon
cat72 = Category.create!(name: "🍌")     # banana
cat73 = Category.create!(name: "🍊")     # orange/ tangerine
cat74 = Category.create!(name: "🍍")     # pineapple
cat75 = Category.create!(name: "🍎")     # apple
cat76 = Category.create!(name: "🍑")     # peach/ peachy
cat77 = Category.create!(name: "🍒")     # cherry
cat78 = Category.create!(name: "🍓")     # strawberry
cat79 = Category.create!(name: "🍅")     # tomato/ bloody mary's
cat81 = Category.create!(name: "🍄")     # mushroom
cat82 = Category.create!(name: "🍔")     # burger
cat83 = Category.create!(name: "🍟")     # french fries/ chips
cat84 = Category.create!(name: "🍕")     # pizza
cat85 = Category.create!(name: "🍱")     # chinese/ japanese 
cat86 = Category.create!(name: "🍜")     # chinese/ japanese
cat87 = Category.create!(name: "🍝")     # spaghetti
cat88 = Category.create!(name: "🍣")     # sushi
cat89 = Category.create!(name: "🍨")     # ice cream 
cat90 = Category.create!(name: "🍦")     # mr whippy 
cat91 = Category.create!(name: "🍩")     # doughnut
cat92 = Category.create!(name: "🍪")     # cookie 
cat93 = Category.create!(name: "🎂")     # birthday/ cake
cat94 = Category.create!(name: "🍰")     # cake
cat95 = Category.create!(name: "🍫")     # chocalate 
cat96 = Category.create!(name: "🍭")     # candy 
cat97 = Category.create!(name: "☕")     # tea/ coffee
cat98 = Category.create!(name: "🍷")     # wine
cat99 = Category.create!(name: "🍸")     # cocktails
cat100 = Category.create!(name: "🍹")     # tropical cocktails
cat101 = Category.create!(name: "🍺")     # beer
cat102 = Category.create!(name: "🍻")     # beers
cat103 = Category.create!(name: "🍴")     # dining
cat104 = Category.create!(name: "🍳")     # cooking  
cat105 = Category.create!(name: "🎪")     # circus     ACTIVITY
cat106 = Category.create!(name: "🎭")     # drama
cat107 = Category.create!(name: "🎨")     # art/ arty
cat108 = Category.create!(name: "🎰")     # gambling
cat109 = Category.create!(name: "🚣")     # rowing
cat110 = Category.create!(name: "🎯")     # bullseye/ direct hit
cat111 = Category.create!(name: "⚽")     # football 
cat112 = Category.create!(name: "⚾")     # baseball
cat113 = Category.create!(name: "🏀")     # basketball
cat114 = Category.create!(name: "🏈")     # american football  
cat115 = Category.create!(name: "🏉")     # rugby ball
cat116 = Category.create!(name: "🎾")     # tennis
cat117 = Category.create!(name: "🎱")     # snooker
cat118 = Category.create!(name: "🎳")     # bowling
cat119 = Category.create!(name: "⛳")     # golf
cat120 = Category.create!(name: "🎣")     # fishing
cat121 = Category.create!(name: "🏊")     # swimming
cat122 = Category.create!(name: "🚴")     # cycling
cat123 = Category.create!(name: "🏆")     # trophy/ champion/ champ
cat124 = Category.create!(name: "🎮")     # gaming
cat125 = Category.create!(name: "🎲")     # poker/ dicey/ dice
cat126 = Category.create!(name: "🎷")     # saxophone/ jazz
cat127 = Category.create!(name: "🎸")     # guitar/ rock n roll
cat128 = Category.create!(name: "🎬")     # filming/ movies
cat129 = Category.create!(name: "🎺")     # trumpet/ regal
cat130 = Category.create!(name: "🌋")     # volcano   TRAVEL & PLACES
cat131 = Category.create!(name: "🏠")     # home
cat132 = Category.create!(name: "⛪")     # church
cat133 = Category.create!(name: "🏢")     # offices
cat134 = Category.create!(name: "🏥")     # hospital
cat135 = Category.create!(name: "🏨")     # hotel
cat136 = Category.create!(name: "🏫")     # school
cat137 = Category.create!(name: "🏰")     # castle
cat138 = Category.create!(name: "💒")     # wedding
cat139 = Category.create!(name: "🗽")     # statue of liberty
cat140 = Category.create!(name: "⛲")     # fountain
cat141 = Category.create!(name: "🌃")     # city night
cat142 = Category.create!(name: "🌆")     # city dusk
cat143 = Category.create!(name: "🌇")     # city sunrise
cat144 = Category.create!(name: "🎠")     # carousel
cat145 = Category.create!(name: "🎡")     # ferris wheel
cat146 = Category.create!(name: "🎢")     # roller coaster/ theme park
cat147 = Category.create!(name: "🚂")     # old school train
cat148 = Category.create!(name: "🚆")     # more modern train
cat149 = Category.create!(name: "🚇")     # underground/ subway/ tube
cat150 = Category.create!(name: "🚌")     # bus
cat151 = Category.create!(name: "🚐")     # minibus
cat152 = Category.create!(name: "🚑")     # ambulance
cat153 = Category.create!(name: "🚒")     # fire engine
cat154 = Category.create!(name: "🚓")     # police car
cat155 = Category.create!(name: "🚕")     # taxi
cat156 = Category.create!(name: "🚗")     # car 
cat157 = Category.create!(name: "🚜")     # tractor
cat158 = Category.create!(name: "🚲")     # bicycle
cat159 = Category.create!(name: "⛽")     # fuel pump/ petrol station
cat160 = Category.create!(name: "⚓")     # nautical/ sea related/ 
cat161 = Category.create!(name: "w⚓")    # w-anchor = wanker
cat162 = Category.create!(name: "⛵")     # sailboat
cat163 = Category.create!(name: "🚤")     # speedboat
cat164 = Category.create!(name: "🚢")     # ship
cat165 = Category.create!(name: "✈️")     # airplane
cat166 = Category.create!(name: "🚁")     # helicopter/ chopper
cat167 = Category.create!(name: "🚠")     # cable car
cat168 = Category.create!(name: "🚀")     # rocket
cat169 = Category.create!(name: "🚧")     # construction sign/ stop
cat170 = Category.create!(name: "🚦")     # traffic lights
cat171 = Category.create!(name: "💵 ")    # dollars
cat172 = Category.create!(name: "💶")     # euros
cat173 = Category.create!(name: "💷")     # pounds
cat174 = Category.create!(name: "💣")     # the bomb/ dropped a bomb
cat175 = Category.create!(name: "💎")     # gem 
cat176 = Category.create!(name: "☠")      # skull & crossbones  
cat177 = Category.create!(name: "🗿")     # tribal
cat178 = Category.create!(name: "🚽")     # loo
cat179 = Category.create!(name: "🚿")     # shower
cat180 = Category.create!(name: "⌛")     # hourglass/ time
cat181 = Category.create!(name: "⏰")     # clock
cat182 = Category.create!(name: "🎈")     # balloon 
cat183 = Category.create!(name: "🎉")     # party popper
cat184 = Category.create!(name: "🎁")     # present
cat185 = Category.create!(name: "📻")     # radio
cat186 = Category.create!(name: "📱")     # phone
cat187 = Category.create!(name: "📞")     # call
cat188 = Category.create!(name: "💻")     # computer
cat189 = Category.create!(name: "🎥")     # film
cat190 = Category.create!(name: "📺")     # television
cat191 = Category.create!(name: "📺")     # television
cat192 = Category.create!(name: "📺")     # television
cat193 = Category.create!(name: "📺")     # television
cat194 = Category.create!(name: "📺")     # television
cat195 = Category.create!(name: "📺")     # television
cat196 = Category.create!(name: "📺")     # television
cat197 = Category.create!(name: "📺")     # television
cat198 = Category.create!(name: "📺")     # television
cat199 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television
cat190 = Category.create!(name: "📺")     # television


# Locations
loc1   = Location.create!(name: "London")
loc2   = Location.create!(name: "Paris")
loc3   = Location.create!(name: "New York")
loc4   = Location.create!(name: "Milan")
loc5   = Location.create!(name: "Kenya")
loc6   = Location.create!(name: "Nantucket")
loc7   = Location.create!(name: "Rome")
loc8   = Location.create!(name: "Barcelona")
loc9   = Location.create!(name: "Auckland")
loc10  = Location.create!(name: "St. Tropez")
loc10  = Location.create!(name: "The Isle of Mull")
loc11  = Location.create!(name: "St. Moritz")
loc12  = Location.create!(name: "Kos")
loc13  = Location.create!(name: "Corfu")
loc14  = Location.create!(name: "Mallorca")
loc15  = Location.create!(name: "Cuba")
loc16  = Location.create!(name: "Costa Rica")
loc17  = Location.create!(name: "Buenos Aires")
loc18  = Location.create!(name: "Hamptons")
loc19  = Location.create!(name: "Windsor")
loc20  = Location.create!(name: "Watamu")
loc21  = Location.create!(name: "Nanyuki")
loc22  = Location.create!(name: "Panama")
loc23  = Location.create!(name: "San Pedro")
loc24  = Location.create!(name: "Martel")
loc25  = Location.create!(name: "Belize")
loc26  = Location.create!(name: "Meribel")
loc27  = Location.create!(name: "Val d'Isere")
loc28  = Location.create!(name: "Chamonix")
loc29  = Location.create!(name: "Zurs")
loc30  = Location.create!(name: "Verbier")
loc31  = Location.create!(name: "Porto Erecole")
loc32  = Location.create!(name: "Porto")
loc33  = Location.create!(name: "Lisbon")
loc34  = Location.create!(name: "Houston")
loc35  = Location.create!(name: "Amsterdam")
loc36  = Location.create!(name: "Copenhagen")
loc37  = Location.create!(name: "London")
loc38  = Location.create!(name: "Athens")
loc39  = Location.create!(name: "Houston")
loc40  = Location.create!(name: "Dallas")
loc41  = Location.create!(name: "Denver")
loc42  = Location.create!(name: "Colorado")
loc43  = Location.create!(name: "Aspen")
loc44  = Location.create!(name: "St. Barths")
loc45  = Location.create!(name: "Slades Farm, Guildford")
loc46  = Location.create!(name: "Carlton Drive, Putney")
# loc47  = Location.create!(name: "London")
# loc48  = Location.create!(name: "Paris")
# loc49  = Location.create!(name: "Paris")
# loc40  = Location.create!(name: "London")
# loc51  = Location.create!(name: "Paris")
# loc52  = Location.create!(name: "London")
# loc53  = Location.create!(name: "Paris")
# loc54  = Location.create!(name: "Paris")
# loc55  = Location.create!(name: "London")
# loc56  = Location.create!(name: "Paris")
# loc57  = Location.create!(name: "London")
# loc58  = Location.create!(name: "Paris")
# loc59  = Location.create!(name: "Paris")
# loc50  = Location.create!(name: "London")
# loc61  = Location.create!(name: "Paris")
# loc62  = Location.create!(name: "London")
# loc63  = Location.create!(name: "Paris")
# loc64  = Location.create!(name: "Paris")
# loc65  = Location.create!(name: "London")
# loc66  = Location.create!(name: "Paris")
# loc67  = Location.create!(name: "London")
# loc68  = Location.create!(name: "Paris")
# loc69  = Location.create!(name: "Paris")
# loc60  = Location.create!(name: "London")
# loc71  = Location.create!(name: "Paris")
# loc72  = Location.create!(name: "London")
# loc73  = Location.create!(name: "Paris")
# loc74  = Location.create!(name: "Paris")
# loc75  = Location.create!(name: "London")
# loc76  = Location.create!(name: "Paris")
# loc77  = Location.create!(name: "London")
# loc78  = Location.create!(name: "Paris")
# loc79  = Location.create!(name: "Paris")
# loc70  = Location.create!(name: "London")
# loc81  = Location.create!(name: "Paris")
# loc82  = Location.create!(name: "London")
# loc83  = Location.create!(name: "Paris")
# loc84  = Location.create!(name: "Paris")
# loc85  = Location.create!(name: "London")
# loc86  = Location.create!(name: "Paris")
# loc87  = Location.create!(name: "London")
# loc88  = Location.create!(name: "Paris")
# loc89  = Location.create!(name: "Paris")
# loc90  = Location.create!(name: "London")
# loc91  = Location.create!(name: "Paris")
# loc92  = Location.create!(name: "London")
# loc93  = Location.create!(name: "Paris")
# loc94  = Location.create!(name: "Paris")
# loc95  = Location.create!(name: "London")
# loc96  = Location.create!(name: "Paris")
# loc97  = Location.create!(name: "London")
# loc98  = Location.create!(name: "Paris")
# loc99  = Location.create!(name: "Paris")
# loc100 = Location.create!(name: "London")
# loc101 = Location.create!(name: "Paris")
# loc102 = Location.create!(name: "London")
# loc103 = Location.create!(name: "Paris")
# loc104 = Location.create!(name: "Paris")
# loc105 = Location.create!(name: "London")
# loc106 = Location.create!(name: "Paris")
# loc107 = Location.create!(name: "London")
# loc108 = Location.create!(name: "Paris")
# loc109 = Location.create!(name: "Paris")
# loc110 = Location.create!(name: "London")
# loc111 = Location.create!(name: "Paris")
# loc22 = Location.create!(name: "London")
# loc23 = Location.create!(name: "Paris")
# loc24 = Location.create!(name: "Paris")
# loc25 = Location.create!(name: "London")
# loc26 = Location.create!(name: "Paris")
# loc27 = Location.create!(name: "London")
# loc28 = Location.create!(name: "Paris")
# loc29 = Location.create!(name: "Paris")
# loc20 = Location.create!(name: "London")
# loc21 = Location.create!(name: "Paris")
# loc22 = Location.create!(name: "London")
# loc23 = Location.create!(name: "Paris")
# loc24 = Location.create!(name: "Paris")
# loc25 = Location.create!(name: "London")
# loc26 = Location.create!(name: "Paris")
# loc27 = Location.create!(name: "London")
# loc28 = Location.create!(name: "Paris")
# loc29 = Location.create!(name: "Paris")
# loc20 = Location.create!(name: "London")
# loc21 = Location.create!(name: "Paris")
# loc22 = Location.create!(name: "London")
# loc23 = Location.create!(name: "Paris")
# loc24 = Location.create!(name: "Paris")
# loc25 = Location.create!(name: "London")
# loc26 = Location.create!(name: "Paris")
# loc27 = Location.create!(name: "London")
# loc28 = Location.create!(name: "Paris")
# loc29 = Location.create!(name: "Paris")
# loc20 = Location.create!(name: "London")
# loc21 = Location.create!(name: "Paris")
# loc22 = Location.create!(name: "London")
# loc23 = Location.create!(name: "Paris")
# loc24 = Location.create!(name: "Paris")
# loc25 = Location.create!(name: "London")
# loc26 = Location.create!(name: "Paris")
# loc27 = Location.create!(name: "London")
# loc28 = Location.create!(name: "Paris")
# loc29 = Location.create!(name: "Paris")
